### ISSUE TITLE
left-right keystrokes no longer working

### ISSUE THREAD

**Issue by ahkok** [ikeydoherty/columbiad#3]
This has been known for a few months, just documenting the issue here.

I'm wondering if all this "lists are always up-down" navigation style that's been corrupting interfaces over the past years has caused this. Up-Down keys actually work, but we use it to navigate to the "power" button.

**Comment by ghost** [comment]
Not sure if/when a fix will be committed, and too lazy to make a PR, but I've posted an explanation of this particular issue and the necessary code to fix this [here](https://www.reddit.com/r/GTK/comments/851sye/broken_kbd_navigation_in_a_gtkflowbox_based_app_i/dvuc7v5/).

**Comment by sofar** [comment]
dis is fixed in the branch

**Comment by sofar** [comment]
ha, no, solution here though:

https://www.reddit.com/r/GTK/comments/851sye/broken_kbd_navigation_in_a_gtkflowbox_based_app_i/

**Comment by ahkok** [comment]
My fork carries the fix
